### ISSUE TITLE
The server is performing cleanups very fast.

### ISSUE THREAD

**Issue by sukhchain9935** [betajs/mock-file-server#2]
Hello, 
I have a problem using mock-file-server. When I upload my file it gets cleaned up immediately, Is there a way to slow down this cleanup by an hour?

**Comment by oliverfriedmann** [comment]
Sure, see the options here: https://github.com/betajs/mock-file-server/blob/master/server.js#L6-L7

**Comment by sukhchain9935** [comment]
For some reason, the files I'm uploading aren't being stored in any of the directories. Can you tell me in which folder are images stored?

**Comment by oliverfriedmann** [comment]
Hi,

as it says in the README: "Files are stored in the memory of the server for a short time and are then removed."

This server is not intended as a real file server but for testing your file upload requests / cors issues and things like that.

Cheers

**Comment by oliverfriedmann** [comment]
There must be countless of file servers out there, but you can use this one here: https://github.com/Jsonize/nano-media-server which is intended for video, but you can upload arbitrary files.

**Comment by sukhchain9935** [comment]
THANKS
